name: Lottery API Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Update TwoCharms Day
        run: |
          python3 << 'EOF'
          import requests

          url = "https://wordpresswebapi.azurewebsites.net/api/ElectronicDrawing/ElectronicDrawingDateSearch/2/2026-06-18/2026-06-19%2023:59"

          data = requests.get(url).json()
          last = data[-1]

          api_date = last["drawingDate"][:10]

          result = last["results"].zfill(2)

          p1 = result[0]
          p2 = result[1]

          new_row = f"{api_date},{p1},{p2},{result}"

          with open("csv/twocharms_day.csv", "r") as f:
              rows = f.read().strip().splitlines()

          last_csv_row = rows[-1]
          last_csv_date = last_csv_row.split(",")[0]

          print("LAST CSV DATE:", last_csv_date)
          print("API DATE:", api_date)

          if api_date > last_csv_date:

              print("UPDATE REQUIRED: YES")

              with open("csv/twocharms_day.csv", "a") as f:
                  f.write("\n" + new_row)

              print("ROW ADDED:", new_row)

          else:

              print("UPDATE REQUIRED: NO")
          EOF

      - name: Commit and Push
        run: |
          git config user.name "LotteryMap Bot"
          git config user.email "actions@github.com"

          git add csv/twocharms_day.csv

          git diff --staged --quiet || git commit -m "Auto update twocharms_day"

          git push
